---

csv: train.csv
data_dir: numbers2

# Datasets
train_data: train_data.csv
val_data: val_data.csv

weights: checkpoints/model_best.pt

# Training
epochs: 300
val_size: 0.2
batch_size: 32
learning_rate: 1e-4
weight_decay: 0.00001
checkpoint_dir: checkpoints/
log_dir: logs/
max_length: 416

spec_params:
  sr: 16000
  n_mels: 64
  n_fft: 320
  win_length: 320
  hop_length: 160
